name: Build Go App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - DEV
          - UAT
          - PROD
        default: DEV

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: DonGranda/reuseable_workflow/.github/workflows/build-acr-aks.yml@v2.0.0
    secrets: inherit